version: "3.8"

services:
  test-master:
    build:
      context: .
      dockerfile: tests/Dockerfile
    environment:
      - NODE_ENV=test
      - CLUSTER_ROLE=master
      - TEST_TYPE=integration
    volumes:
      - .:/app
    working_dir: /app
    command: npm run test:integration

  test-worker-1:
    build:
      context: .
      dockerfile: tests/Dockerfile
    environment:
      - NODE_ENV=test
      - CLUSTER_ROLE=worker
      - WORKER_ID=1
      - TEST_TYPE=integration
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - test-master
    command: npm run test:integration

  test-worker-2:
    build:
      context: .
      dockerfile: tests/Dockerfile
    environment:
      - NODE_ENV=test
      - CLUSTER_ROLE=worker
      - WORKER_ID=2
      - TEST_TYPE=integration
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - test-master
    command: npm run test:integration

  test-highload:
    build:
      context: .
      dockerfile: tests/Dockerfile
    environment:
      - NODE_ENV=test
      - TEST_TYPE=highload
    volumes:
      - .:/app
    working_dir: /app
    command: npm run test:highload
